; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
	duinowitchery/hd44780@^1.3.2
	adafruit/DHT sensor library@^1.4.6
	bblanchon/ArduinoJson@^6.21.0
	bogde/HX711@^0.7.5

[env:usb]
extends = env:esp32dev
upload_protocol = esptool
upload_port = COM3
lib_deps = 
	knolleary/PubSubClient@^2.8
	duinowitchery/hd44780@^1.3.2
	adafruit/DHT sensor library@^1.4.6
	bblanchon/ArduinoJson@^6.21.0
	bogde/HX711@^0.7.5

[env:ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.6.45
upload_flags =
    --auth=biltong123
lib_deps = 
	knolleary/PubSubClient@^2.8
	duinowitchery/hd44780@^1.3.2
	adafruit/DHT sensor library@^1.4.6
	bblanchon/ArduinoJson@^6.21.0
	bogde/HX711@^0.7.5
